# Site Info
site:
  theme_color: '#009688' # 网站主题色，例如 theme_color: '#009688'

# Header
nav:
  - title: 书架
    icon: ri-book-2-fill
    url: /books
  - title: 说说
    icon: ri-instagram-fill
    url: /memos
  - title: 留言
    icon: ri-message-3-fill
    url: /comments
  - title: 标签
    icon: ri-price-tag-3-fill
    url: /tags
  - title: 友链
    icon: ri-emotion-happy-fill
    url: /links

# Algolia search
algolia_search:
  enable: true
  hits:
    per_page: 6

flow_bg: true

post_abstract:
  enable: true
  key: semb5AhNssX2qdKJZQek

# Conversion between Traditional and Simplified Chinese (簡繁轉換)
translate:
  enable: true
  # The text of a button
  default: 繁
  # the language of website (1 - Traditional Chinese/ 2 - Simplified Chinese）
  defaultEncoding: 2
  # Time delay
  translateDelay: 0
  # The text of the button when the language is Simplified Chinese
  msgToTraditionalChinese: '繁'
  # The text of the button when the language is Traditional Chinese
  msgToSimplifiedChinese: '簡'

# copy settings
# copyright: Add the copyright information after copied content (複製的內容後面加上版權信息)
copy:
  enable: true
  copyright:
    enable: true
    limit_count: 50

# Displays outdated notice for a post (文章過期提醒)
noticeOutdate:
  enable: true
  style: flat # style: simple/flat
  limit_day: 500 # When will it be shown


# favicon
favicon: https://img.vidorra.life/images/royians/logo.png

# logo
logo: https://img.vidorra.life/images/royians/logo.png

# avatar
avatar: https://img.vidorra.life/images/royians/avatar.jpg

title_font:
  enable: true,
  family: LDL
  font_size: 3.5rem

memos:
  url: https://memos-production-0cda.up.railway.app
  limit: 30
  cover: https://img.vidorra.life/images/covers/tittle-tattle-cover.webp

# links
links:
  Github: https://github.com/ROYIANS
  weibo: https://weibo.com/u/6319184855
  bilibili: https://space.bilibili.com/32267413
  netease-cloud-music: https://y.music.163.com/m/user?id=356590959&dlt=0846&app_version=8.9.10
  wechat: https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzU4NDc1NDIzNA==&scene=124#wechat_redirect
  telegram: https://t.me/s/littleDreamlandPlus
  # ZhiHu:
  # Twitter:
  # Weibo:

# analytics
google_analytics: G-8CY7HEN598
baidu_analytics: fe2db955cb6ff96a6e53b812ac5e9559

# mathjax
fancybox: true

# mathjax
mathjax: true

# echarts
echarts: true

# busuanzi
busuanzi: true

# mermaid
mermaid:
  enable: true
  # Available themes: default | dark | forest | neutral
  theme: default

twikoo:
  enable: true
  envId: https://comment.little-dream.land
  visitor: true

# 非必要請不要修改
CDN:
  internal_provider: local
  third_party_provider: jsdelivr
  version: true
  custom_format:
  option:

# 插入代码到头部 </head> 之前 和 底部 </body> 之前
# 插入额外代码 如：统计，广告等
extends:
  head: # 在head中插入
    - <link href="/fonts/LDL/LDL.css" rel="stylesheet">
    - <meta name="baidu-site-verification" content="codeva-fCRpJWFFlr" />
  body: # 在body中插入
