# Header
nav:
  留言: /comments
  说说: /memos
  标签: /tags
  分类: /categories
  友链: /links

# favicon
favicon: /images/royians/logo.png

# logo
logo: /images/royians/logo.png

# avatar
avatar: /images/royians/avatar.jpg

title_font:
  enable: true,
  family: LDL
  font_size: 3.5rem

memos:
  url: https://vidorra.life
  limit: 30

# links
links:
  Github: https://github.com/xbmlz
  # ZhiHu:
  # Twitter:
  # Weibo:

# analytics
google_analytics: G-8CY7HEN598
baidu_analytics: fe2db955cb6ff96a6e53b812ac5e9559

# mathjax
fancybox: true

# mathjax
mathjax: true

# echarts
echarts: true

# busuanzi
busuanzi: true

# mermaid
mermaid:
  enable: true
  # Available themes: default | dark | forest | neutral
  theme: default

twikoo:
  enable: true
  envId: https://comment.little-dream.land
  visitor: true

# 非必要請不要修改
CDN:
  internal_provider: local
  third_party_provider: jsdelivr
  version: true
  custom_format:
  option:

# 插入代码到头部 </head> 之前 和 底部 </body> 之前
# 插入额外代码 如：统计，广告等
extends:
  head: # 在head中插入
    - <link href="/fonts/LDL/LDL.css" rel="stylesheet">
    - <link rel="preconnect" href="https://fonts.googleapis.com">
    - <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    - <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+SC&family=Noto+Serif+SC&display=swap" rel="stylesheet">
  body: # 在body中插入
